from pathlib import Path
from setuptools import setup, find_packages

# Minimal setup so that `pip install .` works if desired (not required for tests)
this_dir = Path(__file__).parent
long_description = (this_dir / "README.md").read_text() if (this_dir / "README.md").exists() else ""

setup(
    name="thefuck-lite",
    version="0.0.0",
    description="Minimal reimplementation of The Fuck – auto-corrects previous commands",
    long_description=long_description,
    long_description_content_type="text/markdown",
    author="Generated by AI",
    packages=find_packages(),
    python_requires=">=3.8",
    entry_points={
        "console_scripts": [
            "thefuck = thefuck.main:main",
        ]
    },
)