from pygments.token import Token

class DefaultStyle:
    """
    Minimal default style.
    """
    styles = {
        Token.Text:                '',
        Token.Whitespace:          '',
        Token.Error:               'bg:#e3d2d2 #a61717',
        Token.Other:               '',
        Token.Keyword:             'bold #008000',
        Token.Keyword_Constant:    'bold #008000',
        Token.Keyword_Declaration: 'bold #008000',
        Token.Keyword_Namespace:   'bold #008000',
        Token.Keyword_Pseudo:      'bold #008000',
        Token.Keyword_Reserved:    'bold #008000',
        Token.Keyword_Type:        'bold #B00040',
        Token.Name:                '',
        Token.Name_Builtin:        '#008000',
        Token.Name_Function:       '#0000FF',
        Token.Name_Class:          'bold #0000FF',
        Token.Name_Namespace:      'bold #0000FF',
        Token.Name_Exception:      'bold #D2413A',
        Token.Name_Variable:       '#19177C',
        Token.Name_Constant:       '#880000',
        Token.Name_Label:          'bold #A0A000',
        Token.Name_Entity:         'bold #999999',
        Token.Name_Attribute:      '#7D9029',
        Token.Name_Tag:            'bold #008000',
        Token.Name_Decorator:      '#AA22FF',
        Token.Literal:             '',
        Token.Literal_String:      '#BA2121',
        Token.Literal_String_Double: '#BA2121',
        Token.Literal_String_Single: '#BA2121',
        Token.Literal_String_Interpol: '#36acaa',
        Token.Literal_String_Regex: '#808080',
        Token.Literal_String_Symbol: '#19177C',
        Token.Literal_String_Other: '#008000',
        Token.Literal_Number:       '#080',
        Token.Literal_Number_Integer: '#080',
        Token.Literal_Number_Float:  '#080',
        Token.Literal_Number_Hex:    '#080',
        Token.Literal_Number_Oct:    '#080',
        Token.Operator:             '#666666',
        Token.Operator_Word:        'bold #AA22FF',
        Token.Punctuation:          '#666666',
        Token.Comment:              'italic #008000',
        Token.Comment_Multiline:    'italic #008000',
        Token.Comment_Preproc:      'noitalic #008000',
        Token.Comment_Single:       'italic #008000',
        Token.Comment_Special:      'bold italic #008000',
        Token.Generic:              '',
        Token.Generic_Deleted:      '#A00000',
        Token.Generic_Emph:         'italic',
        Token.Generic_Error:        '#FF0000',
        Token.Generic_Heading:      'bold #000080',
        Token.Generic_Insert:       '#00A000',
        Token.Generic_Output:       '#888',
        Token.Generic_Prompt:       'bold #000080',
        Token.Generic_Strong:       'bold',
        Token.Generic_Subheading:   'bold #800080',
        Token.Generic_Traceback:    '#04D',
    }