"""
Celery-like states constants.
"""

PENDING = "PENDING"
RECEIVED = "RECEIVED"
STARTED = "STARTED"
SUCCESS = "SUCCESS"
FAILURE = "FAILURE"
RETRY = "RETRY"
REVOKED = "REVOKED"

READY_STATES = frozenset({SUCCESS, FAILURE, REVOKED})